version: '3.1'

services:
  firebird:
    image: jacobalberty/firebird:2.5
    container_name: firebird25
    ports:
      - "3050:3050"
    environment:
      ISC_PASSWORD: masterkey
    volumes:
      - ./employee.fbk:/firebird/employee.fbk
      - firebird_data:/firebird/data

volumes:
  firebird_data:
